import { createSlice, createAsyncThunk, PayloadAction } from "@reduxjs/toolkit";
import moment from "moment";
import { API_REQUEST_HANDLER } from "../../utils/index";
import { message } from "antd";
import { ACCESS_TOKEN } from "../../constants/user";
export interface IItemFileStockReservation {
  _id: number;
  type: string;
  sku: string;
  title: string;
  stock_on_hand: number;
  available_stock: number;
  reserved_stock: number;
  last_amended_date: string;
  last_amended_user: string;
}

const MockData = [
  {
    _id: 11,
    type: "Wine",
    sku: "Hansssle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 12,
    type: "Wine",
    sku: "Haasdle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 13,
    type: "Wine",
    sku: "Hanssss7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 14,
    type: "Wine",
    sku: "Haasdse7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 15,
    type: "Wine",
    sku: "Han7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 16,
    type: "Wine",
    sku: "asfsdf",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 17,
    type: "Wine",
    sku: "Hansssle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 18,
    type: "Wine",
    sku: "Haasdle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 19,
    type: "Wine",
    sku: "Hanssss7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 20,
    type: "Wine",
    sku: "Haasdse7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 21,
    type: "Wine",
    sku: "Hansssle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 22,
    type: "Wine",
    sku: "Haasdle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 23,
    type: "Wine",
    sku: "Hanssss7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 24,
    type: "Wine",
    sku: "Haasdse7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 25,
    type: "Wine",
    sku: "Han7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 26,
    type: "Wine",
    sku: "asfsdf",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 27,
    type: "Wine",
    sku: "Hansssle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 28,
    type: "Wine",
    sku: "Haasdle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 29,
    type: "Wine",
    sku: "Hanssss7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 30,
    type: "Wine",
    sku: "Haasdse7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 31,
    type: "Wine",
    sku: "Hansssle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 32,
    type: "Wine",
    sku: "Haasdle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 33,
    type: "Wine",
    sku: "Hanssss7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 34,
    type: "Wine",
    sku: "Haasdse7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 35,
    type: "Wine",
    sku: "Han7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 36,
    type: "Wine",
    sku: "asfsdf",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 37,
    type: "Wine",
    sku: "Hansssle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 38,
    type: "Wine",
    sku: "Haasdle7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 39,
    type: "Wine",
    sku: "Hanssss7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
  {
    _id: 40,
    type: "Wine",
    sku: "Haasdse7765",
    title: "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    stock_on_hand: 14200,
    available_stock: 14180,
    reserved_stock: 120,
    last_amended_date: "18/10/2021",
    last_amended_user: "McKinney@alba.com",
  },
];

interface IInitialState {
  data: any | [];
}

const initialState: IInitialState = {
  data: MockData,
};

export const ItemFileStockReservationSlice = createSlice({
  name: "ItemFileStockReservation",
  initialState,
  reducers: {
    fetchItemFileStockReservation: (state: typeof initialState) => {
      state.data = MockData;
    },
    resetItemFileStockReservationState: (state: typeof initialState) => {
      state.data = MockData;
    },
  },
});

// Selectors
// export const getUser = (state: any) => state.users;

// Reducers and actions
export const {
  fetchItemFileStockReservation,
  resetItemFileStockReservationState,
} = ItemFileStockReservationSlice.actions;

export default ItemFileStockReservationSlice.reducer;
