/** @format */

export const userData = [
  {
    key: 1,
    fullName: 'Aktar Wali',
    username: 'AktarWali',
    email: 'manuelsnr@gmail.com',
    depart: 'ALDI',
    powerBiUsername: 'Darlene',
    position: 'Developer',
    client: 'Multiple',
    site: 'CORB',
    roles: '3',
    status: 'Locked',
    action: '...',
  },
  {
    key: 2,
    fullName: 'Marky Marc',
    username: 'MarkyMarc',
    email: 'manuelsnr@gmail.com',
    depart: 'iForce',
    powerBiUsername: 'Angel',
    position: 'Developer',
    client: 'Multiple',
    site: 'CORB',
    roles: '4',
    status: 'Unlocked',
    action: '...',
  },
  {
    key: 3,
    fullName: 'The Vin',
    username: 'TheVin',
    email: 'manuelsnr@gmail.com',
    depart: 'iForce',
    powerBiUsername: 'Darlene',
    position: 'Developer',
    client: 'Multiple',
    site: 'CORB',
    roles: '3',
    status: 'Locked',
    action: '...',
  },
  {
    key: 4,
    fullName: 'Arlene McCoy',
    username: 'McCoy',
    email: 'manuelsnr@gmail.com',
    depart: 'iForce',
    powerBiUsername: 'Darlene',
    position: 'Developer',
    client: 'Multiple',
    site: 'CORB',
    roles: '3',
    status: 'Locked',
    action: '...',
  },
  {
    key: 5,
    fullName: 'Arlene McCoy',
    username: 'McCoy',
    email: 'manuelsnr@gmail.com',
    depart: 'iForce',
    powerBiUsername: 'Darlene',
    position: 'Developer',
    client: 'Multiple',
    site: 'CORB',
    roles: '3',
    status: 'Locked',
    action: '...',
  },
  {
    key: 6,
    fullName: 'Arlene McCoy',
    username: 'McCoy',
    email: 'manuelsnr@gmail.com',
    depart: 'iForce',
    powerBiUsername: 'Darlene',
    position: 'Developer',
    client: 'Multiple',
    site: 'CORB',
    roles: '3',
    status: 'Locked',
    action: '...',
  },
  {
    key: 7,
    fullName: 'Arlene McCoy',
    username: 'McCoy',
    email: 'manuelsnr@gmail.com',
    depart: 'iForce',
    powerBiUsername: 'Darlene',
    position: 'Developer',
    client: 'Multiple',
    site: 'CORB',
    roles: '3',
    status: 'Locked',
    action: '...',
  },
  {
    key: 8,
    fullName: 'Arlene McCoy',
    username: 'McCoy',
    email: 'manuelsnr@gmail.com',
    depart: 'iForce',
    powerBiUsername: 'Darlene',
    position: 'Developer',
    client: 'Multiple',
    site: 'CORB',
    roles: '3',
    status: 'Locked',
    action: '...',
  },
  {
    key: 9,
    fullName: 'Arlene McCoy',
    username: 'McCoy',
    email: 'manuelsnr@gmail.com',
    depart: 'iForce',
    powerBiUsername: 'Darlene',
    position: 'Developer',
    client: 'Multiple',
    site: 'CORB',
    roles: '3',
    status: 'Locked',
    action: '...',
  },
]
